### ISSUE TITLE
May I steal your website design?

### ISSUE THREAD

**Issue by J-Cake** [cberner/cberner-com#1]
Hi, sorry for the slightly informal means of communication. I wasn't able to find an email address anywhere. I checked out your blog and was delighted with a simple, aesthetic style. I'm hoping for your permission to apply a similar style to [mine](https://jschneiderprojects.com.au) when I get it working. 

If you'd prefer to continue this conversation in private, please don't hesitate to contact me under [jakieschneider13@gmail.com](mailto:jakieschneider13@gmail.com)

**Comment by cberner** [comment]
Ya, for sure. The theme is MIT licensed: https://github.com/cberner/hugo-future-imperfect
